name: "[AWS] Deploy to S3"
on:
  push
env:
  BUCKET_NAME: "krajkovic-homepage"
  AWS_REGION: "eu-west-1"
  ACCOUNT_ID: "711387132019"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/Github-Actions-Role
          role-session-name: github-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3 sync ./build s3://${{ env.BUCKET_NAME }}/ --delete
